### PR TITLE
Validate `Contents.IModel`s from Google Drive.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Performs validation on Contents models received from Google Drive.

### CODE REVIEW

**Comment by blink1073** [comment]
Why not use the function exposed in [@jupyterlab/services](https://github.com/jupyterlab/jupyterlab/blob/0ab31a9c9943affddfcfafe95d6c479f96b5123d/packages/services/src/contents/validate.ts#L40)?

**Comment by ian-r-rose** [comment]
I don't believe it is exported at the package level (unless I am missing how to get at it).

I would prefer to do that, if possible.

**Comment by ian-r-rose** [comment]
As it is, I just copied the (relatively short) file.

**Comment by ian-r-rose** [comment]
Ah, nevermind,  I see how to do that now.

**Comment by ian-r-rose** [comment]
@blink1073 Can you comment on the build failure from getting the `validate` functions from `@jupyterlab/services`? It works locally on my machine.

**Comment by blink1073** [comment]
I can replicate locally by removing `packages/all-packages/node_modules` and `packages/jupyterlab-google-drive/node_modules`, then running `npm install && npm run build`.  It looks like the path-based lookup is not being caught by our `tsconfig.json` `paths` config based on reading https://www.typescriptlang.org/docs/handbook/module-resolution.html.  

It works if I add the rule:

```javascript
      "@jupyterlab/services/lib/*": [
        "../services/src/*"
      ],
```

We could add that config for all of our packages, but I think we should stick with the "only import from the top level package" rule.  We can expose the validate functions as static functions on the respective namespaces, and you could inline the code until that is exposed.  How does that sound?

**Comment by ian-r-rose** [comment]
Sure, let's do that. I'd rather not have to do a bunch of path munging in the `tsconfig`s. Since I am tracking master in CI, we would not need to wait too long for them to be exposed.

**Pull request merged**
