### PR TITLE
Update to JupyterLab 2

### PR DESCRIPTION
**Pull request by andrelfpinto**

### CODE REVIEW

**Comment by andrelfpinto** [comment]
Fixes #171

**Comment by arvati** [comment]
Is this project active? Asking if someone are evaluating this PR or not....

**Comment by bmshouse** [comment]
I have reviewed the change, and it looks good to me. My only concern is that this will break backward compatibility.  Can you confirm that this will or will not continue to work with JupyterLab 1? The real developer is busy on other projects, but I will do my best to get your request merged and support for JupyterLab 2 included.

**Comment by cforelle** [comment]
I am not the original poster but it looks like it will break backwards compatibility by requiring jlab >= 2.0.0. That said, it seems like practically all extensions will do so: The jlab [migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html) says updated extensions should require at least 2.0.0. I would imagine users who want to remain on jlab 1 could specify an earlier version of this extension to install.

**Comment by bmshouse** [comment]
@ian-r-rose Pardon my intrusion, but I am not sure how to handle this pull request so that a stable version for JupyterLab v1.x and JupyterLab v2.x are maintained. Tagged versions? Two branches? Please let me know what you think and I will take action.

@cforelle Thank you for looking at this too! Please let me know if you have any recommendations.

@andrelfpinto I appreciate all your work on this. I will continue to push to get make the available.

**Comment by ian-r-rose** [comment]
Sorry for the exceedingly slow look @andrelfpinto. This looks good to me -- I pushed a small tweak to the version numbers.

@arvati This project is still alive, though I have less time to work on it than i used to. There are some imminent changes to the drive API (cf #164), and it's not clear to me whether this will still work after that. At the very least, the Team Drives integration may stop working. Depending on how involved the fix is, it may take little time to respond to or a lot of time.

@bmshouse Thank you for testing and reviewing. This version of the extension will no longer be compatible with JupyterLab 1.0, though users of that will still be able to install older versions. If Google does indeed break the extension by changing their API, then older versions of the extension will definitely stop working, as I doubt we have the bandwidth to maintain two stable tracks.

**Comment by ian-r-rose** [comment]
Thank you for the contribution @andrelfpinto, and sorry again for the slow review. Published as `@jupyterlab/google-drive@2.0.0`.

Thanks again for reviewing @bmshouse

**Comment by bmshouse** [comment]
@ian-r-rose Wow!  Thank you! You did in 1 hour (or less) what would have probably taken me days. Amazing!

**Pull request merged**
