### PR TITLE
Update plugin ids + schemas for new plugin system.

### PR DESCRIPTION
**Pull request by ian-r-rose**

### CODE REVIEW

**Comment by blink1073** [comment]
Changes look good, I'm not sure why it can't find `@jupyterlab/buildutils`...

**Comment by blink1073** [comment]
Ah, because the `/src` won't be there until you run `npm run build`.

**Comment by ian-r-rose** [comment]
I'm not sure I follow. Does you mean I would need to run `build` twice?

**Comment by blink1073** [comment]
You'd need to run it between `npm install` and `npm run addsibling`.

**Comment by ian-r-rose** [comment]
Hmm, still broken. Buildutils is making some assumptions about the paths that don't hold in this case.

**Comment by blink1073** [comment]
Ugh, confirmed locally with `npm run addsibling`

**Comment by blink1073** [comment]
Thanks for being our canary!

**Comment by ian-r-rose** [comment]
:+1:

**Comment by blink1073** [comment]
Mmmm, simpler *and* cleaner, most good.

**Pull request merged**
